## Semantic theme variations shared by authored scenes and runtime-created controls.
class_name UIThemeTypes
extends RefCounted

const DISPLAY_TITLE := &"DisplayTitle"
const SCREEN_TITLE := &"ScreenTitle"
const SECTION_TITLE := &"SectionTitle"
const BODY := &"Body"
const CAPTION := &"Caption"
const DATA := &"Data"
const MODAL_PANEL := &"ModalPanel"
const INSET_PANEL := &"InsetPanel"
const HUD_PANEL := &"HUDPanel"
const CONSOLE_PANEL := &"ConsolePanel"
const TOOLTIP_PANEL := &"TooltipPanel"
const FLOATING_PANEL := &"FloatingPanel"
const PRIMARY_BUTTON := &"PrimaryButton"
const SECONDARY_BUTTON := &"SecondaryButton"
const DESTRUCTIVE_BUTTON := &"DestructiveButton"
const COMPACT_BUTTON := &"CompactButton"
const ICON_BUTTON := &"IconButton"
const INVENTORY_SLOT := &"InventorySlot"
const INVENTORY_SLOT_SELECTED := &"InventorySlotSelected"
const INVENTORY_SLOT_DRAG_SOURCE := &"InventorySlotDragSource"
const INVENTORY_SLOT_DROP_TARGET := &"InventorySlotDropTarget"
const STATUS_SUCCESS := &"StatusSuccess"
const STATUS_WARNING := &"StatusWarning"
const STATUS_ERROR := &"StatusError"
const STATUS_ACTIVE := &"StatusActive"
const STATUS_MUTED := &"StatusMuted"
